<<<<<<< HEAD
# Generated by Django 5.1 on 2024-09-07 17:17
=======
# Generated by Django 5.1.7 on 2025-03-24 11:45
>>>>>>> rater

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('blog', '0004_alter_post_banner'),
=======
        ('blog', '0004_post_likes'),
>>>>>>> rater
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
<<<<<<< HEAD
            field=models.ImageField(blank=True, default='default.png', upload_to='media/'),
=======
            field=models.URLField(),
>>>>>>> rater
        ),
    ]
