# Generated by Django 5.1.7 on 2025-03-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
