# Generated by Django 5.1.7 on 2025-03-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
