# Generated by Django 5.1.7 on 2025-03-29 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(100, message='Content must be at least 100 characters long.'), django.core.validators.MaxLengthValidator(5000, message='Content cannot exceed 2500 characters.')]),
        ),
    ]
