# Generated by Django 6.1 on 2026-09-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment'),
        ('blog', '0012_post_is_published_post_published_at'),
    ]

    operations = [
    ]
